config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    authenticated :user do
      root 'admin/activity_logs#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :admin do
    resources :activity_logs
  end

  namespace :api do
    devise_for :users, skip: %i[registrations sessions passwords]
    devise_scope :user do
      post '/signup', to: 'registrations#create'
      post '/login', to: 'sessions#create'
      delete '/logout', to: "sessions#destroy"
    end
    resources :activities, only:[:index]
    resources :babies, only: [:index] do
      collection do
        get ':id/activity_logs' => :activity_logs, as: :activity_logs
      end
    end
    resources :activity_logs, only: [:create, :update]
  end

end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :activity_logs, dependent: :destroy

end

app/models/activity_log.rb
class ActivityLog < ApplicationRecord
  
  belongs_to :activity
  belongs_to :assistant
  belongs_to :baby

  after_update :calc_duration

  validates :start_time_before_type_cast, format: {
    with:  /\A\d{4}-\d{2}-\d{2} \d{2}:\d{2}\z/
  }, presence: true
  validates :stop_time_before_type_cast, format: {
    with:  /\A\d{4}-\d{2}-\d{2} \d{2}:\d{2}\z/
  }, unless: :stop_time_nil?
  validate :validate_stop_time, unless: :stop_time_nil?

  scope :start_time_desc,     -> { order(start_time: :desc) }
  scope :filter_by_baby,      -> (baby) {joins(:baby).where(babies: {name: baby}) }
  scope :filter_by_assistant, -> (assitant) {joins(:assistant).where(assistants: {name: assitant})}
  scope :filter_by_status,    ->(status){
                                          if status== "finished"
                                            where.not(duration: nil)
                                          elsif status== "in_progress"
                                            where(duration: nil)
                                          elsif status == "all"
                                            all
                                          end
                                        } 

  def validate_stop_time
    if (stop_time <= start_time)
      errors.add(:stop_time, " no puede ser previo al la fecha de inicio")
    end
  end

  def stop_time_nil?
    stop_time.nil?
  end

  def calc_duration
    unless stop_time.nil?
      time_diff = (stop_time - start_time)
      dtion= (time_diff / 1.minute).round
      if update_column("duration", "#{dtion}")
        p "updateo"
      else
        p errors.full_messages
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assistant.rb
class Assistant < ApplicationRecord
  has_many :activity_logs, dependent: :destroy

  scope  :order_name,   -> { order(name: :asc).pluck(:name) }
end

app/models/baby.rb
class Baby < ApplicationRecord
  has_many :activity_logs, dependent: :destroy

  scope  :order_name,   -> {order(name: :asc).pluck(:name) }

  def age_to_months
    total_months = ((Date.today.year * 12 + Date.today.month) - ((birthday.year * 12) + birthday.month))
    age_years = total_months / 12
    age_months = total_months % 12
    a_years= ""
    age_years >= 1 ? a_years= "#{age_years} años" : a_years= ""
    age_months >= 1 ? m_months= "#{age_months} meses" : m_months= ""
    "#{a_years} #{m_months}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include Devise::JWT::RevocationStrategies::JTIMatcher
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: self
end

app/controllers/admin/activity_logs_controller.rb
class Admin::ActivityLogsController < ApplicationController

  def index
    @activity_logs = ActivityLog.start_time_desc.paginate(page: params[:page], per_page: 10)
    filtering_params(params).each do |key, value|
      @activity_logs = @activity_logs.public_send("filter_by_#{key}", value) if value.present?
    end
    @babies = Baby.order_name
    @assistants = Assistant.order_name

  end

  def filtering_params(params)
    params.slice(:baby, :assistant, :status)
  end
end

app/controllers/api/activities_controller.rb
class Api::ActivitiesController < ApiController
  def index
    @activities = Activity.select(:id, :name, :description).paginate(page:params[:page], per_page: 5)
    render json: @activities
  end
end

app/controllers/api/activity_logs_controller.rb
class Api::ActivityLogsController < ApiController
  before_action :set_activity_log, only: [:update]
  
  def create
    @activity_log = ActivityLog.new(params_activity_logs)
    if @activity_log.save
      render json: @activity_log, status: 200
    else
      render json: {error: @activity_log.errors.full_messages}, status: 400
    end                                                                                                   
  end

  def update
    if @activity_log.update(params_activity_logs)
      render json: @activity_log, status: 200
    else
      render json: {error: @activity_log.errors.full_messages}, status: 400
    end
  end

  private
    def params_activity_logs
      params.require(:activity_log).permit(:activity_id, :baby_id, :assistant_id, :start_time, :stop_time, :comments)
    end

    def set_activity_log
      @activity_log = ActivityLog.find(params[:id]) rescue nil
    end
end

app/controllers/api/babies_controller.rb
class Api::BabiesController < ApiController
  before_action :set_baby, only: [:activity_logs]

  def index
    babies = []
    Baby.all.paginate(page:params[:page], per_page: 10).each do |baby|
      age = baby.age_to_months
      babies << {name: baby.name, baby_age: age, father_name: baby.father_name, mother_name: baby.mother_name, address: baby.address, phone: baby.phone}
    end
    render json: babies
  end

  def activity_logs
    activities= []
    if @baby.activity_logs.present?
      @baby.activity_logs.paginate(page:params[:page], per_page: 10).each do |activity_log|
        activity_log.stop_time.present? ? stop_date= activity_log.stop_time : stop_date = ''
        activities << {activity_log_id: activity_log.id, baby_id: @baby.id, assistant: activity_log.assistant.name, start_time: activity_log.start_time.iso8601, stop_time: stop_date}
      end
    else
      activities = {baby_id: @baby.id, alert: "sin actividades"}
    end
    render json: activities
  end

  private

    def set_baby
      @baby = Baby.find(params[:id]) rescue nil
    end
end

app/controllers/api/registrations_controller.rb
class Api::RegistrationsController < Devise::RegistrationsController
  skip_before_action :verify_authenticity_token

  respond_to :json

  def create
    build_resource(sign_up_params)
    resource.save
    render json: resource, status: :created  
  end
end

app/controllers/api/sessions_controller.rb
class Api::SessionsController < Devise::SessionsController
  skip_before_action :verify_authenticity_token

  respond_to :json

  private

    def respond_with(resource, _opts = {})
      render json: resource
    end

    def respond_to_on_destroy
      head :no_content
    end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  #before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  respond_to :json
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "application"
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/activity_logs/index.html.erb
<h1>Log de actividades</h1>
  <%= form_tag admin_activity_logs_path, method: :get, class: "form-inline" do %>
    <div class="col-md-4">
      <div class="input-group mb-3">
        <%= select_tag "baby", options_for_select(@babies, "#{params['baby']}"), prompt: 'Seleccionar bebé', class: "custom-select" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="input-group mb-3">
        <%= select_tag "assistant", options_for_select(@assistants, "#{params['assistant']}"), prompt: 'Seleccionar asistente', class: "custom-select" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="input-group mb-3">
        <%= select_tag "status", options_for_select({"Todos" => "all", "En progreso" => "in_progress", "Terminada" => "finished"}, "#{params['status']}"), prompt: 'Seleccionar estatus', class: "custom-select" %>
      </div>
    </div>
    <div class="col-md-12">
      <%= submit_tag "Filtrar", class: "float-right btn btn-primary" %>
      <%= link_to "Limpiar", admin_activity_logs_path, class: "float-right btn btn-default mr-2" %>
    </div>
  <% end %>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr class="table-primary">
        <th>Bebé</th>
        <th>Asistente</th>
        <th>Actividad</th>
        <th>Inicio</th>
        <th>Estatus</th>
        <th>Duración</th>
      </tr>
    </thead>
    <tbody>
      <% @activity_logs.each do |activity_log| %>
        <tr>
          <td>
            <%= activity_log.baby.name %>
          </td>
          <td>
            <%= activity_log.assistant.name %>
          </td>
          <td>
            <%= activity_log.activity.name %>
          </td>
          <td>
            <%= activity_log.start_time.strftime("%Y-%m-%d %H:%M") %>
          </td>
          <td>
            <%= activity_log.stop_time.nil? ? "En progreso" : "Terminada" %>
          </td>
          <td>
            <%= activity_log.duration.nil? ? "*" : activity_log.duration %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="digg_pagination">
  <%= will_paginate @activity_logs, :container => false %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Kinedu Test</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <div class="session">
      <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
     <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render "layouts/nav"%>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </div>
</html>